@base_url = http://localhost:8085/api/v1

@access_token = eyJ0eXAiOiJKV1QiLCJhbGciOiJFUzM4NCJ9.eyJzdWIiOiJkMDU2NTllYi0wMDdmLTQyYmYtOTZhOC02MDA1ZDk4NDBhMjIiLCJhcHBsaWNhdGlvbl9pZCI6IiIsImNsaWVudF9pZCI6IiIsImV4cCI6MTczMDQwNDU3OSwiaWF0IjoxNzMwMzY4NTc5LCJuYmYiOjE3MzAzNjg1Nzl9.ZuVsBiX1rypsMBxBmjicfIMUaKc54T40i2gTyftncaqKXXnBpDkjk82aI2eg9mYDaM9-ZocSO-xMVF4jjPM6fRIbRh2SHYP7DKO3nmyf9O-TtAsV9d70xQL0tNK8SdGZ
@refresh_token = 11114a9c-522b-4c98-93fd-7ccb5b02e64e
@password_reset_token = 5fba7305-3024-4766-859a-eabeaf72a3df

@user_id = d05659eb-007f-42bf-96a8-6005d9840a22
@email = user@example.com
@password = 1A,R;(9h0Y&gYH5=7eY!gg

# ================ User ================

# Get user token
POST {{base_url}}/token
Content-Type: application/json

{
  "email": "{{email}}",
  "password": "{{password}}"
}

###

# Refresh user token
POST {{base_url}}/refresh-token/{{refresh_token}}
Content-Type: application/json

###

# Forgotten password
POST {{base_url}}/forgotten-password/{{email}}
Content-Type: application/json

###

# Update password
PATCH {{base_url}}/update-password
Content-Type: application/json

{
  "token": "{{password_reset_token}}",
  "password": "{{password}}"
}

###

# ================ Users ================

# List all users
GET {{base_url}}/users?p=1&l=10&s=-created_at
Content-Type: application/json
Authorization: Bearer {{access_token}}

###

# List all deleted users
GET {{base_url}}/users/deleted?p=1&l=10&s=-created_at
Content-Type: application/json
Authorization: Bearer {{access_token}}

###

# Create a new user
POST {{base_url}}/users
Content-Type: application/json
Authorization: Bearer {{access_token}}

{
  "lastname": "Test",
  "firstname": "Test",
  "email": "test@test.com",
  "password": "Aa1234568!;kgHGh1487=d454$d4"
}

###

# Get user by ID
GET {{base_url}}/users/{{user_id}}
Content-Type: application/json
Authorization: Bearer {{access_token}}

###

# Delete a user
DELETE {{base_url}}/users/{{user_id}}
Content-Type: application/json
Authorization: Bearer {{access_token}}

###

# Restore a deleted user
PATCH {{base_url}}/users/{{user_id}}/restore
Content-Type: application/json
Authorization: Bearer {{access_token}}

###
