[workspace]
resolver = "2"
members = ["domain"]

[workspace.package]
version = "0.1.0"
edition = "2021"
authors = ["Fabien Bellanger <valentil@gmail.com>"]
repository = "https://github.com/fabienbellanger/auth2-api"
readme = "./README.md"
