name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

env:
  CARGO_TERM_COLOR: always
  SQLX_OFFLINE: true

jobs:
  rust-build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: .
    services:
      mysql:
        image: mariadb:latest
        env:
          MYSQL_ROOT_PASSWORD: root
          MYSQL_DATABASE: auth2_api
        ports:
          - 3306:3306
      maildev:
        image: djfarrelly/maildev
        ports:
          - 1081:80
          - 1025:25
    steps:
      - uses: actions/checkout@v4

      - name: Extract Rust version from Cargo.toml
        run: |
          RUST_VERSION=$(sed -n 's/^rust-version = "\([^"]*\)"/\1/p' Cargo.toml)
          echo "rust-version: $RUST_VERSION"
          echo "RUST_VERSION=$RUST_VERSION" >> $GITHUB_ENV

      - name: Install Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: ${{ env.RUST_VERSION }}
          override: true

      - name: Fmt
        run: |
          rustup component add rustfmt
          cargo fmt

      - name: Clippy
        run: |
          rustup component add clippy
          cargo clippy

      - name: Run tests
        run: DATABASE_URL=mysql://root:root@127.0.0.1:3306/auth2_api cargo test --verbose

      - name: Build
        run: cargo build --verbose
